### PR TITLE
Make sure dependencies for raspi-teletext are present

### PR DESCRIPTION
**Pull request by stuiterveer**
If someone has Raspberry Pi OS Lite installed, the necessary development packages needed for raspi-teletext are not installed. This makes compilation fail, but vbit2 doesn't detect the fail resulting in a broken vbit2 service. Added a step that does install these packages.

### CODE REVIEW

**Comment by ZXGuesser** [comment]
Can you provide more details on the behaviour you're seeing? I just tried installing on the latest legacy lite image (2023-12-05-raspios-bullseye-armhf-lite.img) which compiled without errors with the default packages.
Also `raspberrypi-dev` doesn't appear to exist.

**Comment by stuiterveer** [comment]
I have to double-check the full context when I'm at home and can check the command history, since it does seem like `raspberrypi-dev` is not present even in the latest OS. Stay tuned for that.

However, there are issues while compiling at least on the latest Lite OS. There _seemingly_ aren't any errors, however you'll notice that the vbit2 service will crash automatically on start. This is because the raspi-teletext can't fully compile everything as long as the development headers are missing.

**Comment by ZXGuesser** [comment]
My understanding was that it is no longer possible to boot bookworm with the legacy broadcom video driver, but I guess I should actually prove that for myself.

**Comment by ZXGuesser** [comment]
My understanding was that it is no longer possible to boot bookworm with the legacy broadcom video driver, but I guess I should have actually proven that for myself...
The package in question will have been `libraspberrypi-dev`

**Comment by stuiterveer** [comment]
I just found out the reason again. Raspi-teletext compilation specifically requires `bcm_host.h` to be present, which it isn't in (at least the latest) Raspberry Pi OS Lite. I followed this answer to solve that dependency issue: https://raspberrypi.stackexchange.com/a/60459. Apparently I commited an incorrect package name, and it should be `libraspberrypi-dev`. This is located in the repositories for the current and legacy versions. I'll update my commit.

**Comment by ZXGuesser** [comment]
I'm on it now 🙂
There are other changes in bookworm which require additional tweaking of the install script to set things up correctly from a clean image, but thanks for prodding me to actually test it rather than take what other people say at face value! 🤦‍♂️

**Comment by stuiterveer** [comment]
Hey no worries! Overall I found that vbit itself works fully taking these changes (and manually tweaking some things for the video-out to work by default). Of course the script itself can use some overall tweaks to work a bit more flexible and in a more expected manner, but I would say it's pretty solid in its current form even for bookworm.

**Pull request closed without merging**
